### ISSUE TITLE
Required login for quotes not working

### ISSUE THREAD

**Issue by ins0** [christinang89/wfh-ninja#1]
The required login (from the docs) for `quote?all=true` isn't working.

http://wfh.ninja/quote?all=true

returns a list of all quotes

**Comment by bencxr** [comment]
Hey Marco,

Thanks for the input - we'll fix it in time, but are having to deal with
some load issues for now.

Thanks
Ben

**Comment by ins0** [comment]
yes, I can imagine that :smile: 

offtopic: glad to see you fixed the security issue right away :+1:

**Comment by christinang89** [comment]
hey @ins0, i looked into it and quote?all=true returns a list of all quotes in the db (both active and inactive) if you're logged in. if you're not logged in, it returns only the active quotes in the db. hope this clarifies. i'll update the documentation, thanks for pointing it out! :smile:

**Comment by ins0** [comment]
indeed that make sense now :smile_cat:
